version: "3.3"
services:

  backend_test:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "8000:8000"
    environment:
      DB_URL: "mongodb://root:example@mongo/"
      DB_NAME: farmstack
      AUTH_JWT_ALGORITHM: HS256
      AUTH_API_MANAGE_USERS: "True"
      AUTH_SECRET_KEY: someverylongsecretkeyhereyes
      ADMIN_USERNAME: admin@kucukdev.org
      ADMIN_PASSWORD: thisisonlyfordevelopment
    networks:
      - app-network

  mongo:
    image: mongo:bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
    volumes:
      - mongo-data-test:/data/db
    command: mongod --quiet --logpath /dev/null # to ignore the log outputs from the MongoDB container
    ports:
      - "27017:27017"

networks:
  app-network:
    driver: bridge
    internal: false

volumes:
  mongo-data-test:
