version: '3.3'
services:
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      DB_URL: 'mongodb://root:example@mongo/'
      DB_NAME: farmstack
    networks:
      - app-network
  mongo:
    image: mongo:bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
    internal: false
