version: "3.3"
services:

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile.test
    ports:
      - "8000:8000"
    environment:
      DB_URL: "mongodb://root:example@mongo/"
      DB_NAME: farmstack
      SECRET_KEY: "TEST_SECRET_KEY"
    networks:
      - app-network

  mongo:
    image: mongo:bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    networks:
      - app-network
    volumes:
      - mongo-data-test:/data/db

networks:
  app-network:
    driver: bridge
    internal: false

volumes:
  mongo-data-test: