FROM python:3.8.9-buster AS scheduler-builder
RUN wget http://prdownloads.sourceforge.net/swig/swig-4.0.2.tar.gz
RUN tar -xvf swig-4.0.2.tar.gz
RUN cd swig-4.0.2 && ./configure && make && make install
COPY scheduler_library /tmp/
RUN cd /tmp/ && make

FROM python:3.8-buster

WORKDIR /usr/src/app

COPY requirements.test.txt ./
RUN pip install --no-cache-dir -r requirements.test.txt

COPY . .
COPY --from=scheduler-builder /tmp/_scheduler.so /tmp/scheduler.py ./

# run the tests with verbose

CMD [ "pytest" ,"-vv"]