/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.SemesterAPIModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('SemesterAPIModel', function() {
    it('should create an instance of SemesterAPIModel', function() {
      // uncomment below and update the code to test SemesterAPIModel
      //var instane = new FastApi.SemesterAPIModel();
      //expect(instance).to.be.a(FastApi.SemesterAPIModel);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FastApi.SemesterAPIModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new FastApi.SemesterAPIModel();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "startDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new FastApi.SemesterAPIModel();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "endDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instance = new FastApi.SemesterAPIModel();
      //expect(instance).to.be();
    });

    it('should have the property startHour (base name: "startHour")', function() {
      // uncomment below and update the code to test the property startHour
      //var instance = new FastApi.SemesterAPIModel();
      //expect(instance).to.be();
    });

    it('should have the property dLesson (base name: "dLesson")', function() {
      // uncomment below and update the code to test the property dLesson
      //var instance = new FastApi.SemesterAPIModel();
      //expect(instance).to.be();
    });

    it('should have the property dBreak (base name: "dBreak")', function() {
      // uncomment below and update the code to test the property dBreak
      //var instance = new FastApi.SemesterAPIModel();
      //expect(instance).to.be();
    });

    it('should have the property slotCount (base name: "slotCount")', function() {
      // uncomment below and update the code to test the property slotCount
      //var instance = new FastApi.SemesterAPIModel();
      //expect(instance).to.be();
    });

  });

}));
