/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.UniversityCurriculumModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UniversityCurriculumModel', function() {
    it('should create an instance of UniversityCurriculumModel', function() {
      // uncomment below and update the code to test UniversityCurriculumModel
      //var instane = new FastApi.UniversityCurriculumModel();
      //expect(instance).to.be.a(FastApi.UniversityCurriculumModel);
    });

    it('should have the property id (base name: "_id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new FastApi.UniversityCurriculumModel();
      //expect(instance).to.be();
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new FastApi.UniversityCurriculumModel();
      //expect(instance).to.be();
    });

    it('should have the property startYear (base name: "startYear")', function() {
      // uncomment below and update the code to test the property startYear
      //var instance = new FastApi.UniversityCurriculumModel();
      //expect(instance).to.be();
    });

    it('should have the property endYear (base name: "endYear")', function() {
      // uncomment below and update the code to test the property endYear
      //var instance = new FastApi.UniversityCurriculumModel();
      //expect(instance).to.be();
    });

    it('should have the property semesters (base name: "semesters")', function() {
      // uncomment below and update the code to test the property semesters
      //var instance = new FastApi.UniversityCurriculumModel();
      //expect(instance).to.be();
    });

  });

}));
