/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import AbsenceModel from './model/AbsenceModel';
import CurriculumLessonModel from './model/CurriculumLessonModel';
import CurriculumSemesterModel from './model/CurriculumSemesterModel';
import HTTPValidationError from './model/HTTPValidationError';
import LessonAPIModel from './model/LessonAPIModel';
import LessonAbsenceModel from './model/LessonAbsenceModel';
import LessonModel from './model/LessonModel';
import Message from './model/Message';
import MessageCreate from './model/MessageCreate';
import SemesterAPIModel from './model/SemesterAPIModel';
import SlotModel from './model/SlotModel';
import Token from './model/Token';
import UniversityAPIModel from './model/UniversityAPIModel';
import UniversityCurriculumModel from './model/UniversityCurriculumModel';
import UniversityDepartmentModel from './model/UniversityDepartmentModel';
import UniversityLessonAPIModel from './model/UniversityLessonAPIModel';
import UniversityLessonModel from './model/UniversityLessonModel';
import UniversityModel from './model/UniversityModel';
import UniversitySectionAPIModel from './model/UniversitySectionAPIModel';
import UniversitySectionModel from './model/UniversitySectionModel';
import UniversitySemesterModel from './model/UniversitySemesterModel';
import UniversitySlotModel from './model/UniversitySlotModel';
import UpdateEntranceYearModel from './model/UpdateEntranceYearModel';
import UpdateLessonModel from './model/UpdateLessonModel';
import UpdatePasswordModel from './model/UpdatePasswordModel';
import UpdateSemesterModel from './model/UpdateSemesterModel';
import UpdateUniversityModel from './model/UpdateUniversityModel';
import UpdateUniversityNameModel from './model/UpdateUniversityNameModel';
import UpdateUserSemesterModel from './model/UpdateUserSemesterModel';
import UserAPIModel from './model/UserAPIModel';
import UserModel from './model/UserModel';
import UserSemesterModel from './model/UserSemesterModel';
import ValidationError from './model/ValidationError';
import CurriculumLessonsApi from './api/CurriculumLessonsApi';
import CurriculumSemestersApi from './api/CurriculumSemestersApi';
import CurriculumsApi from './api/CurriculumsApi';
import DepartmentsApi from './api/DepartmentsApi';
import LessonsApi from './api/LessonsApi';
import SchedulerApi from './api/SchedulerApi';
import SemestersApi from './api/SemestersApi';
import TokenApi from './api/TokenApi';
import UniversitiesApi from './api/UniversitiesApi';
import UniversityLessonsApi from './api/UniversityLessonsApi';
import UniversitySectionsApi from './api/UniversitySectionsApi';
import UniversitySemestersApi from './api/UniversitySemestersApi';
import UsersApi from './api/UsersApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var Kucukdevapi = require('index'); // See note below*.
* var xxxSvc = new Kucukdevapi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new Kucukdevapi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new Kucukdevapi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new Kucukdevapi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The AbsenceModel model constructor.
     * @property {module:model/AbsenceModel}
     */
    AbsenceModel,

    /**
     * The CurriculumLessonModel model constructor.
     * @property {module:model/CurriculumLessonModel}
     */
    CurriculumLessonModel,

    /**
     * The CurriculumSemesterModel model constructor.
     * @property {module:model/CurriculumSemesterModel}
     */
    CurriculumSemesterModel,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The LessonAPIModel model constructor.
     * @property {module:model/LessonAPIModel}
     */
    LessonAPIModel,

    /**
     * The LessonAbsenceModel model constructor.
     * @property {module:model/LessonAbsenceModel}
     */
    LessonAbsenceModel,

    /**
     * The LessonModel model constructor.
     * @property {module:model/LessonModel}
     */
    LessonModel,

    /**
     * The Message model constructor.
     * @property {module:model/Message}
     */
    Message,

    /**
     * The MessageCreate model constructor.
     * @property {module:model/MessageCreate}
     */
    MessageCreate,

    /**
     * The SemesterAPIModel model constructor.
     * @property {module:model/SemesterAPIModel}
     */
    SemesterAPIModel,

    /**
     * The SlotModel model constructor.
     * @property {module:model/SlotModel}
     */
    SlotModel,

    /**
     * The Token model constructor.
     * @property {module:model/Token}
     */
    Token,

    /**
     * The UniversityAPIModel model constructor.
     * @property {module:model/UniversityAPIModel}
     */
    UniversityAPIModel,

    /**
     * The UniversityCurriculumModel model constructor.
     * @property {module:model/UniversityCurriculumModel}
     */
    UniversityCurriculumModel,

    /**
     * The UniversityDepartmentModel model constructor.
     * @property {module:model/UniversityDepartmentModel}
     */
    UniversityDepartmentModel,

    /**
     * The UniversityLessonAPIModel model constructor.
     * @property {module:model/UniversityLessonAPIModel}
     */
    UniversityLessonAPIModel,

    /**
     * The UniversityLessonModel model constructor.
     * @property {module:model/UniversityLessonModel}
     */
    UniversityLessonModel,

    /**
     * The UniversityModel model constructor.
     * @property {module:model/UniversityModel}
     */
    UniversityModel,

    /**
     * The UniversitySectionAPIModel model constructor.
     * @property {module:model/UniversitySectionAPIModel}
     */
    UniversitySectionAPIModel,

    /**
     * The UniversitySectionModel model constructor.
     * @property {module:model/UniversitySectionModel}
     */
    UniversitySectionModel,

    /**
     * The UniversitySemesterModel model constructor.
     * @property {module:model/UniversitySemesterModel}
     */
    UniversitySemesterModel,

    /**
     * The UniversitySlotModel model constructor.
     * @property {module:model/UniversitySlotModel}
     */
    UniversitySlotModel,

    /**
     * The UpdateEntranceYearModel model constructor.
     * @property {module:model/UpdateEntranceYearModel}
     */
    UpdateEntranceYearModel,

    /**
     * The UpdateLessonModel model constructor.
     * @property {module:model/UpdateLessonModel}
     */
    UpdateLessonModel,

    /**
     * The UpdatePasswordModel model constructor.
     * @property {module:model/UpdatePasswordModel}
     */
    UpdatePasswordModel,

    /**
     * The UpdateSemesterModel model constructor.
     * @property {module:model/UpdateSemesterModel}
     */
    UpdateSemesterModel,

    /**
     * The UpdateUniversityModel model constructor.
     * @property {module:model/UpdateUniversityModel}
     */
    UpdateUniversityModel,

    /**
     * The UpdateUniversityNameModel model constructor.
     * @property {module:model/UpdateUniversityNameModel}
     */
    UpdateUniversityNameModel,

    /**
     * The UpdateUserSemesterModel model constructor.
     * @property {module:model/UpdateUserSemesterModel}
     */
    UpdateUserSemesterModel,

    /**
     * The UserAPIModel model constructor.
     * @property {module:model/UserAPIModel}
     */
    UserAPIModel,

    /**
     * The UserModel model constructor.
     * @property {module:model/UserModel}
     */
    UserModel,

    /**
     * The UserSemesterModel model constructor.
     * @property {module:model/UserSemesterModel}
     */
    UserSemesterModel,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The CurriculumLessonsApi service constructor.
    * @property {module:api/CurriculumLessonsApi}
    */
    CurriculumLessonsApi,

    /**
    * The CurriculumSemestersApi service constructor.
    * @property {module:api/CurriculumSemestersApi}
    */
    CurriculumSemestersApi,

    /**
    * The CurriculumsApi service constructor.
    * @property {module:api/CurriculumsApi}
    */
    CurriculumsApi,

    /**
    * The DepartmentsApi service constructor.
    * @property {module:api/DepartmentsApi}
    */
    DepartmentsApi,

    /**
    * The LessonsApi service constructor.
    * @property {module:api/LessonsApi}
    */
    LessonsApi,

    /**
    * The SchedulerApi service constructor.
    * @property {module:api/SchedulerApi}
    */
    SchedulerApi,

    /**
    * The SemestersApi service constructor.
    * @property {module:api/SemestersApi}
    */
    SemestersApi,

    /**
    * The TokenApi service constructor.
    * @property {module:api/TokenApi}
    */
    TokenApi,

    /**
    * The UniversitiesApi service constructor.
    * @property {module:api/UniversitiesApi}
    */
    UniversitiesApi,

    /**
    * The UniversityLessonsApi service constructor.
    * @property {module:api/UniversityLessonsApi}
    */
    UniversityLessonsApi,

    /**
    * The UniversitySectionsApi service constructor.
    * @property {module:api/UniversitySectionsApi}
    */
    UniversitySectionsApi,

    /**
    * The UniversitySemestersApi service constructor.
    * @property {module:api/UniversitySemestersApi}
    */
    UniversitySemestersApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
