/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Kucukdevapi);
  }
}(this, function(expect, Kucukdevapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Kucukdevapi.LessonsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('LessonsApi', function() {
    describe('createAbsence', function() {
      it('should call createAbsence successfully', function(done) {
        //uncomment below and update the code to test createAbsence
        //instance.createAbsence(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('createLesson', function() {
      it('should call createLesson successfully', function(done) {
        //uncomment below and update the code to test createLesson
        //instance.createLesson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteAbsence', function() {
      it('should call deleteAbsence successfully', function(done) {
        //uncomment below and update the code to test deleteAbsence
        //instance.deleteAbsence(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteLesson', function() {
      it('should call deleteLesson successfully', function(done) {
        //uncomment below and update the code to test deleteLesson
        //instance.deleteLesson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSingleLesson', function() {
      it('should call getSingleLesson successfully', function(done) {
        //uncomment below and update the code to test getSingleLesson
        //instance.getSingleLesson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listLessonsOfSemester', function() {
      it('should call listLessonsOfSemester successfully', function(done) {
        //uncomment below and update the code to test listLessonsOfSemester
        //instance.listLessonsOfSemester(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateLesson', function() {
      it('should call updateLesson successfully', function(done) {
        //uncomment below and update the code to test updateLesson
        //instance.updateLesson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
