/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.UniversityLessonsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UniversityLessonsApi', function() {
    describe('createUniversityLesson', function() {
      it('should call createUniversityLesson successfully', function(done) {
        //uncomment below and update the code to test createUniversityLesson
        //instance.createUniversityLesson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUniversityLesson', function() {
      it('should call deleteUniversityLesson successfully', function(done) {
        //uncomment below and update the code to test deleteUniversityLesson
        //instance.deleteUniversityLesson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSingleLessonWithCode', function() {
      it('should call getSingleLessonWithCode successfully', function(done) {
        //uncomment below and update the code to test getSingleLessonWithCode
        //instance.getSingleLessonWithCode(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSingleUniversitySemesterLesson', function() {
      it('should call getSingleUniversitySemesterLesson successfully', function(done) {
        //uncomment below and update the code to test getSingleUniversitySemesterLesson
        //instance.getSingleUniversitySemesterLesson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUniversitySemesterLessons', function() {
      it('should call listUniversitySemesterLessons successfully', function(done) {
        //uncomment below and update the code to test listUniversitySemesterLessons
        //instance.listUniversitySemesterLessons(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUniversityLesson', function() {
      it('should call updateUniversityLesson successfully', function(done) {
        //uncomment below and update the code to test updateUniversityLesson
        //instance.updateUniversityLesson(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
