/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.Kucukdevapi);
  }
}(this, function(expect, Kucukdevapi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new Kucukdevapi.UniversitiesApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UniversitiesApi', function() {
    describe('createUniversity', function() {
      it('should call createUniversity successfully', function(done) {
        //uncomment below and update the code to test createUniversity
        //instance.createUniversity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUniversity', function() {
      it('should call deleteUniversity successfully', function(done) {
        //uncomment below and update the code to test deleteUniversity
        //instance.deleteUniversity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getCurrentUniversitySemester', function() {
      it('should call getCurrentUniversitySemester successfully', function(done) {
        //uncomment below and update the code to test getCurrentUniversitySemester
        //instance.getCurrentUniversitySemester(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSingleUniversity', function() {
      it('should call getSingleUniversity successfully', function(done) {
        //uncomment below and update the code to test getSingleUniversity
        //instance.getSingleUniversity(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUniversities', function() {
      it('should call listUniversities successfully', function(done) {
        //uncomment below and update the code to test listUniversities
        //instance.listUniversities(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUniversityCurrentSemester', function() {
      it('should call updateUniversityCurrentSemester successfully', function(done) {
        //uncomment below and update the code to test updateUniversityCurrentSemester
        //instance.updateUniversityCurrentSemester(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUniversityName', function() {
      it('should call updateUniversityName successfully', function(done) {
        //uncomment below and update the code to test updateUniversityName
        //instance.updateUniversityName(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
