/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.FastApi);
  }
}(this, function(expect, FastApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new FastApi.UniversitySemestersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('UniversitySemestersApi', function() {
    describe('createUniversitySemester', function() {
      it('should call createUniversitySemester successfully', function(done) {
        //uncomment below and update the code to test createUniversitySemester
        //instance.createUniversitySemester(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('deleteUniversitySemester', function() {
      it('should call deleteUniversitySemester successfully', function(done) {
        //uncomment below and update the code to test deleteUniversitySemester
        //instance.deleteUniversitySemester(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('getSingleUniversitySemesters', function() {
      it('should call getSingleUniversitySemesters successfully', function(done) {
        //uncomment below and update the code to test getSingleUniversitySemesters
        //instance.getSingleUniversitySemesters(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('listUniversitySemesters', function() {
      it('should call listUniversitySemesters successfully', function(done) {
        //uncomment below and update the code to test listUniversitySemesters
        //instance.listUniversitySemesters(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('updateUniversitySemester', function() {
      it('should call updateUniversitySemester successfully', function(done) {
        //uncomment below and update the code to test updateUniversitySemester
        //instance.updateUniversitySemester(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
