/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AbsenceModel model module.
 * @module model/AbsenceModel
 * @version 1.0.0
 */
class AbsenceModel {
    /**
     * Constructs a new <code>AbsenceModel</code>.
     * @alias module:model/AbsenceModel
     * @param absence {String} 
     */
    constructor(absence) { 
        
        AbsenceModel.initialize(this, absence);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, absence) { 
        obj['absence'] = absence;
    }

    /**
     * Constructs a <code>AbsenceModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AbsenceModel} obj Optional instance to populate.
     * @return {module:model/AbsenceModel} The populated <code>AbsenceModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AbsenceModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('absence')) {
                obj['absence'] = ApiClient.convertToType(data['absence'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
AbsenceModel.prototype['_id'] = undefined;

/**
 * @member {String} absence
 */
AbsenceModel.prototype['absence'] = undefined;






export default AbsenceModel;

