/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CurriculumLessonModel from './CurriculumLessonModel';

/**
 * The CurriculumSemesterModel model module.
 * @module model/CurriculumSemesterModel
 * @version 1.0.0
 */
class CurriculumSemesterModel {
    /**
     * Constructs a new <code>CurriculumSemesterModel</code>.
     * @alias module:model/CurriculumSemesterModel
     * @param semester {Number} 
     */
    constructor(semester) { 
        
        CurriculumSemesterModel.initialize(this, semester);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, semester) { 
        obj['semester'] = semester;
    }

    /**
     * Constructs a <code>CurriculumSemesterModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CurriculumSemesterModel} obj Optional instance to populate.
     * @return {module:model/CurriculumSemesterModel} The populated <code>CurriculumSemesterModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CurriculumSemesterModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('semester')) {
                obj['semester'] = ApiClient.convertToType(data['semester'], 'Number');
            }
            if (data.hasOwnProperty('lessons')) {
                obj['lessons'] = ApiClient.convertToType(data['lessons'], [CurriculumLessonModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
CurriculumSemesterModel.prototype['_id'] = undefined;

/**
 * @member {Number} semester
 */
CurriculumSemesterModel.prototype['semester'] = undefined;

/**
 * @member {Array.<module:model/CurriculumLessonModel>} lessons
 */
CurriculumSemesterModel.prototype['lessons'] = undefined;






export default CurriculumSemesterModel;

