/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The LessonAPIModel model module.
 * @module model/LessonAPIModel
 * @version 1.0.0
 */
class LessonAPIModel {
    /**
     * Constructs a new <code>LessonAPIModel</code>.
     * @alias module:model/LessonAPIModel
     */
    constructor() { 
        
        LessonAPIModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>LessonAPIModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LessonAPIModel} obj Optional instance to populate.
     * @return {module:model/LessonAPIModel} The populated <code>LessonAPIModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LessonAPIModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('instructor')) {
                obj['instructor'] = ApiClient.convertToType(data['instructor'], 'String');
            }
            if (data.hasOwnProperty('absenceLimit')) {
                obj['absenceLimit'] = ApiClient.convertToType(data['absenceLimit'], 'Number');
            }
            if (data.hasOwnProperty('slots')) {
                obj['slots'] = ApiClient.convertToType(data['slots'], [['Number']]);
            }
            if (data.hasOwnProperty('absences')) {
                obj['absences'] = ApiClient.convertToType(data['absences'], [['Number']]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
LessonAPIModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
LessonAPIModel.prototype['name'] = undefined;

/**
 * @member {String} instructor
 */
LessonAPIModel.prototype['instructor'] = undefined;

/**
 * @member {Number} absenceLimit
 */
LessonAPIModel.prototype['absenceLimit'] = undefined;

/**
 * @member {Array.<Array.<Number>>} slots
 */
LessonAPIModel.prototype['slots'] = undefined;

/**
 * @member {Array.<Array.<Number>>} absences
 */
LessonAPIModel.prototype['absences'] = undefined;






export default LessonAPIModel;

