/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AbsenceModel from './AbsenceModel';

/**
 * The LessonAbsenceModel model module.
 * @module model/LessonAbsenceModel
 * @version 1.0.0
 */
class LessonAbsenceModel {
    /**
     * Constructs a new <code>LessonAbsenceModel</code>.
     * @alias module:model/LessonAbsenceModel
     * @param absence {module:model/AbsenceModel} 
     */
    constructor(absence) { 
        
        LessonAbsenceModel.initialize(this, absence);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, absence) { 
        obj['absence'] = absence;
    }

    /**
     * Constructs a <code>LessonAbsenceModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/LessonAbsenceModel} obj Optional instance to populate.
     * @return {module:model/LessonAbsenceModel} The populated <code>LessonAbsenceModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new LessonAbsenceModel();

            if (data.hasOwnProperty('absence')) {
                obj['absence'] = AbsenceModel.constructFromObject(data['absence']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/AbsenceModel} absence
 */
LessonAbsenceModel.prototype['absence'] = undefined;






export default LessonAbsenceModel;

