/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MessageCreate model module.
 * @module model/MessageCreate
 * @version 1.0.0
 */
class MessageCreate {
    /**
     * Constructs a new <code>MessageCreate</code>.
     * @alias module:model/MessageCreate
     * @param id {String} 
     * @param message {String} 
     */
    constructor(id, message) { 
        
        MessageCreate.initialize(this, id, message);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, message) { 
        obj['_id'] = id;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>MessageCreate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageCreate} obj Optional instance to populate.
     * @return {module:model/MessageCreate} The populated <code>MessageCreate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageCreate();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
MessageCreate.prototype['_id'] = undefined;

/**
 * @member {String} message
 */
MessageCreate.prototype['message'] = undefined;






export default MessageCreate;

