/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The SemesterAPIModel model module.
 * @module model/SemesterAPIModel
 * @version 1.0.0
 */
class SemesterAPIModel {
    /**
     * Constructs a new <code>SemesterAPIModel</code>.
     * @alias module:model/SemesterAPIModel
     */
    constructor() { 
        
        SemesterAPIModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>SemesterAPIModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SemesterAPIModel} obj Optional instance to populate.
     * @return {module:model/SemesterAPIModel} The populated <code>SemesterAPIModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SemesterAPIModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('startHour')) {
                obj['startHour'] = ApiClient.convertToType(data['startHour'], 'String');
            }
            if (data.hasOwnProperty('dLesson')) {
                obj['dLesson'] = ApiClient.convertToType(data['dLesson'], 'Number');
            }
            if (data.hasOwnProperty('dBreak')) {
                obj['dBreak'] = ApiClient.convertToType(data['dBreak'], 'Number');
            }
            if (data.hasOwnProperty('slotCount')) {
                obj['slotCount'] = ApiClient.convertToType(data['slotCount'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
SemesterAPIModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
SemesterAPIModel.prototype['name'] = undefined;

/**
 * @member {Date} startDate
 */
SemesterAPIModel.prototype['startDate'] = undefined;

/**
 * @member {Date} endDate
 */
SemesterAPIModel.prototype['endDate'] = undefined;

/**
 * @member {String} startHour
 */
SemesterAPIModel.prototype['startHour'] = undefined;

/**
 * @member {Number} dLesson
 */
SemesterAPIModel.prototype['dLesson'] = undefined;

/**
 * @member {Number} dBreak
 */
SemesterAPIModel.prototype['dBreak'] = undefined;

/**
 * @member {Number} slotCount
 */
SemesterAPIModel.prototype['slotCount'] = undefined;






export default SemesterAPIModel;

