/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UniversityAPIModel model module.
 * @module model/UniversityAPIModel
 * @version 1.0.0
 */
class UniversityAPIModel {
    /**
     * Constructs a new <code>UniversityAPIModel</code>.
     * @alias module:model/UniversityAPIModel
     */
    constructor() { 
        
        UniversityAPIModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UniversityAPIModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityAPIModel} obj Optional instance to populate.
     * @return {module:model/UniversityAPIModel} The populated <code>UniversityAPIModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityAPIModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('curSemesterID')) {
                obj['curSemesterID'] = ApiClient.convertToType(data['curSemesterID'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UniversityAPIModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
UniversityAPIModel.prototype['name'] = undefined;

/**
 * @member {String} curSemesterID
 */
UniversityAPIModel.prototype['curSemesterID'] = undefined;






export default UniversityAPIModel;

