/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UniversityLessonAPIModel from './UniversityLessonAPIModel';

/**
 * The UniversitySemesterModel model module.
 * @module model/UniversitySemesterModel
 * @version 1.0.0
 */
class UniversitySemesterModel {
    /**
     * Constructs a new <code>UniversitySemesterModel</code>.
     * @alias module:model/UniversitySemesterModel
     * @param name {String} 
     */
    constructor(name) { 
        
        UniversitySemesterModel.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>UniversitySemesterModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversitySemesterModel} obj Optional instance to populate.
     * @return {module:model/UniversitySemesterModel} The populated <code>UniversitySemesterModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversitySemesterModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('lessons')) {
                obj['lessons'] = ApiClient.convertToType(data['lessons'], [UniversityLessonAPIModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UniversitySemesterModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
UniversitySemesterModel.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/UniversityLessonAPIModel>} lessons
 */
UniversitySemesterModel.prototype['lessons'] = undefined;






export default UniversitySemesterModel;

