/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CurriculumSemesterModel from './CurriculumSemesterModel';

/**
 * The UniversityCurriculumModel model module.
 * @module model/UniversityCurriculumModel
 * @version 1.0.0
 */
class UniversityCurriculumModel {
    /**
     * Constructs a new <code>UniversityCurriculumModel</code>.
     * @alias module:model/UniversityCurriculumModel
     * @param name {String} 
     * @param startYear {Number} 
     * @param endYear {Number} 
     */
    constructor(name, startYear, endYear) { 
        
        UniversityCurriculumModel.initialize(this, name, startYear, endYear);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, startYear, endYear) { 
        obj['name'] = name;
        obj['startYear'] = startYear;
        obj['endYear'] = endYear;
    }

    /**
     * Constructs a <code>UniversityCurriculumModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityCurriculumModel} obj Optional instance to populate.
     * @return {module:model/UniversityCurriculumModel} The populated <code>UniversityCurriculumModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityCurriculumModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('startYear')) {
                obj['startYear'] = ApiClient.convertToType(data['startYear'], 'Number');
            }
            if (data.hasOwnProperty('endYear')) {
                obj['endYear'] = ApiClient.convertToType(data['endYear'], 'Number');
            }
            if (data.hasOwnProperty('semesters')) {
                obj['semesters'] = ApiClient.convertToType(data['semesters'], [CurriculumSemesterModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UniversityCurriculumModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
UniversityCurriculumModel.prototype['name'] = undefined;

/**
 * @member {Number} startYear
 */
UniversityCurriculumModel.prototype['startYear'] = undefined;

/**
 * @member {Number} endYear
 */
UniversityCurriculumModel.prototype['endYear'] = undefined;

/**
 * @member {Array.<module:model/CurriculumSemesterModel>} semesters
 */
UniversityCurriculumModel.prototype['semesters'] = undefined;






export default UniversityCurriculumModel;

