/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UniversityDepartmentModel from './UniversityDepartmentModel';
import UniversitySemesterModel from './UniversitySemesterModel';

/**
 * The UniversityModel model module.
 * @module model/UniversityModel
 * @version 1.0.0
 */
class UniversityModel {
    /**
     * Constructs a new <code>UniversityModel</code>.
     * @alias module:model/UniversityModel
     * @param name {String} 
     */
    constructor(name) { 
        
        UniversityModel.initialize(this, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name) { 
        obj['name'] = name;
    }

    /**
     * Constructs a <code>UniversityModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityModel} obj Optional instance to populate.
     * @return {module:model/UniversityModel} The populated <code>UniversityModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('departments')) {
                obj['departments'] = ApiClient.convertToType(data['departments'], [UniversityDepartmentModel]);
            }
            if (data.hasOwnProperty('semesters')) {
                obj['semesters'] = ApiClient.convertToType(data['semesters'], [UniversitySemesterModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UniversityModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
UniversityModel.prototype['name'] = undefined;

/**
 * @member {Array.<module:model/UniversityDepartmentModel>} departments
 */
UniversityModel.prototype['departments'] = undefined;

/**
 * @member {Array.<module:model/UniversitySemesterModel>} semesters
 */
UniversityModel.prototype['semesters'] = undefined;






export default UniversityModel;

