/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UniversitySlotModel from './UniversitySlotModel';

/**
 * The UniversityLessonModel model module.
 * @module model/UniversityLessonModel
 * @version 1.0.0
 */
class UniversityLessonModel {
    /**
     * Constructs a new <code>UniversityLessonModel</code>.
     * @alias module:model/UniversityLessonModel
     * @param name {String} 
     * @param code {String} 
     * @param ects {Number} 
     * @param absenceLimit {Number} 
     * @param section {String} 
     * @param instructor {String} 
     * @param slots {Array.<module:model/UniversitySlotModel>} 
     */
    constructor(name, code, ects, absenceLimit, section, instructor, slots) { 
        
        UniversityLessonModel.initialize(this, name, code, ects, absenceLimit, section, instructor, slots);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, code, ects, absenceLimit, section, instructor, slots) { 
        obj['name'] = name;
        obj['code'] = code;
        obj['ects'] = ects;
        obj['absenceLimit'] = absenceLimit;
        obj['section'] = section;
        obj['instructor'] = instructor;
        obj['slots'] = slots;
    }

    /**
     * Constructs a <code>UniversityLessonModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityLessonModel} obj Optional instance to populate.
     * @return {module:model/UniversityLessonModel} The populated <code>UniversityLessonModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityLessonModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('ects')) {
                obj['ects'] = ApiClient.convertToType(data['ects'], 'Number');
            }
            if (data.hasOwnProperty('absenceLimit')) {
                obj['absenceLimit'] = ApiClient.convertToType(data['absenceLimit'], 'Number');
            }
            if (data.hasOwnProperty('section')) {
                obj['section'] = ApiClient.convertToType(data['section'], 'String');
            }
            if (data.hasOwnProperty('instructor')) {
                obj['instructor'] = ApiClient.convertToType(data['instructor'], 'String');
            }
            if (data.hasOwnProperty('slots')) {
                obj['slots'] = ApiClient.convertToType(data['slots'], [UniversitySlotModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UniversityLessonModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
UniversityLessonModel.prototype['name'] = undefined;

/**
 * @member {String} code
 */
UniversityLessonModel.prototype['code'] = undefined;

/**
 * @member {Number} ects
 */
UniversityLessonModel.prototype['ects'] = undefined;

/**
 * @member {Number} absenceLimit
 */
UniversityLessonModel.prototype['absenceLimit'] = undefined;

/**
 * @member {String} section
 */
UniversityLessonModel.prototype['section'] = undefined;

/**
 * @member {String} instructor
 */
UniversityLessonModel.prototype['instructor'] = undefined;

/**
 * @member {Array.<module:model/UniversitySlotModel>} slots
 */
UniversityLessonModel.prototype['slots'] = undefined;






export default UniversityLessonModel;

