/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UniversitySlotModel model module.
 * @module model/UniversitySlotModel
 * @version 1.0.0
 */
class UniversitySlotModel {
    /**
     * Constructs a new <code>UniversitySlotModel</code>.
     * @alias module:model/UniversitySlotModel
     * @param day {Number} 
     * @param hour {Number} 
     * @param isLab {Number} 
     */
    constructor(day, hour, isLab) { 
        
        UniversitySlotModel.initialize(this, day, hour, isLab);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, day, hour, isLab) { 
        obj['day'] = day;
        obj['hour'] = hour;
        obj['isLab'] = isLab;
    }

    /**
     * Constructs a <code>UniversitySlotModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversitySlotModel} obj Optional instance to populate.
     * @return {module:model/UniversitySlotModel} The populated <code>UniversitySlotModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversitySlotModel();

            if (data.hasOwnProperty('day')) {
                obj['day'] = ApiClient.convertToType(data['day'], 'Number');
            }
            if (data.hasOwnProperty('hour')) {
                obj['hour'] = ApiClient.convertToType(data['hour'], 'Number');
            }
            if (data.hasOwnProperty('isLab')) {
                obj['isLab'] = ApiClient.convertToType(data['isLab'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} day
 */
UniversitySlotModel.prototype['day'] = undefined;

/**
 * @member {Number} hour
 */
UniversitySlotModel.prototype['hour'] = undefined;

/**
 * @member {Number} isLab
 */
UniversitySlotModel.prototype['isLab'] = undefined;






export default UniversitySlotModel;

