/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import UniversitySectionModel from './UniversitySectionModel';

/**
 * The UniversityAPILessonModel model module.
 * @module model/UniversityAPILessonModel
 * @version 1.0.0
 */
class UniversityAPILessonModel {
    /**
     * Constructs a new <code>UniversityAPILessonModel</code>.
     * @alias module:model/UniversityAPILessonModel
     * @param name {String} 
     * @param code {String} 
     * @param ects {Number} 
     * @param absenceLimit {Number} 
     */
    constructor(name, code, ects, absenceLimit) { 
        
        UniversityAPILessonModel.initialize(this, name, code, ects, absenceLimit);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, code, ects, absenceLimit) { 
        obj['name'] = name;
        obj['code'] = code;
        obj['ects'] = ects;
        obj['absenceLimit'] = absenceLimit;
    }

    /**
     * Constructs a <code>UniversityAPILessonModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UniversityAPILessonModel} obj Optional instance to populate.
     * @return {module:model/UniversityAPILessonModel} The populated <code>UniversityAPILessonModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UniversityAPILessonModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('ects')) {
                obj['ects'] = ApiClient.convertToType(data['ects'], 'Number');
            }
            if (data.hasOwnProperty('absenceLimit')) {
                obj['absenceLimit'] = ApiClient.convertToType(data['absenceLimit'], 'Number');
            }
            if (data.hasOwnProperty('sections')) {
                obj['sections'] = ApiClient.convertToType(data['sections'], [UniversitySectionModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UniversityAPILessonModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
UniversityAPILessonModel.prototype['name'] = undefined;

/**
 * @member {String} code
 */
UniversityAPILessonModel.prototype['code'] = undefined;

/**
 * @member {Number} ects
 */
UniversityAPILessonModel.prototype['ects'] = undefined;

/**
 * @member {Number} absenceLimit
 */
UniversityAPILessonModel.prototype['absenceLimit'] = undefined;

/**
 * @member {Array.<module:model/UniversitySectionModel>} sections
 */
UniversityAPILessonModel.prototype['sections'] = undefined;






export default UniversityAPILessonModel;

