/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateSemesterModel model module.
 * @module model/UpdateSemesterModel
 * @version 1.0.0
 */
class UpdateSemesterModel {
    /**
     * Constructs a new <code>UpdateSemesterModel</code>.
     * @alias module:model/UpdateSemesterModel
     * @param curSemesterID {String} 
     */
    constructor(curSemesterID) { 
        
        UpdateSemesterModel.initialize(this, curSemesterID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, curSemesterID) { 
        obj['curSemesterID'] = curSemesterID;
    }

    /**
     * Constructs a <code>UpdateSemesterModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateSemesterModel} obj Optional instance to populate.
     * @return {module:model/UpdateSemesterModel} The populated <code>UpdateSemesterModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateSemesterModel();

            if (data.hasOwnProperty('curSemesterID')) {
                obj['curSemesterID'] = ApiClient.convertToType(data['curSemesterID'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} curSemesterID
 */
UpdateSemesterModel.prototype['curSemesterID'] = undefined;






export default UpdateSemesterModel;

