/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdatePasswordModel model module.
 * @module model/UpdatePasswordModel
 * @version 1.0.0
 */
class UpdatePasswordModel {
    /**
     * Constructs a new <code>UpdatePasswordModel</code>.
     * @alias module:model/UpdatePasswordModel
     * @param password {String} 
     */
    constructor(password) { 
        
        UpdatePasswordModel.initialize(this, password);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, password) { 
        obj['password'] = password;
    }

    /**
     * Constructs a <code>UpdatePasswordModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdatePasswordModel} obj Optional instance to populate.
     * @return {module:model/UpdatePasswordModel} The populated <code>UpdatePasswordModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdatePasswordModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UpdatePasswordModel.prototype['_id'] = undefined;

/**
 * @member {String} password
 */
UpdatePasswordModel.prototype['password'] = undefined;






export default UpdatePasswordModel;

