/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateEntranceYearModel model module.
 * @module model/UpdateEntranceYearModel
 * @version 1.0.0
 */
class UpdateEntranceYearModel {
    /**
     * Constructs a new <code>UpdateEntranceYearModel</code>.
     * @alias module:model/UpdateEntranceYearModel
     * @param entranceYear {Number} 
     */
    constructor(entranceYear) { 
        
        UpdateEntranceYearModel.initialize(this, entranceYear);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, entranceYear) { 
        obj['entranceYear'] = entranceYear;
    }

    /**
     * Constructs a <code>UpdateEntranceYearModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateEntranceYearModel} obj Optional instance to populate.
     * @return {module:model/UpdateEntranceYearModel} The populated <code>UpdateEntranceYearModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateEntranceYearModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('entranceYear')) {
                obj['entranceYear'] = ApiClient.convertToType(data['entranceYear'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UpdateEntranceYearModel.prototype['_id'] = undefined;

/**
 * @member {Number} entranceYear
 */
UpdateEntranceYearModel.prototype['entranceYear'] = undefined;






export default UpdateEntranceYearModel;

