/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UpdateUniversityModel model module.
 * @module model/UpdateUniversityModel
 * @version 1.0.0
 */
class UpdateUniversityModel {
    /**
     * Constructs a new <code>UpdateUniversityModel</code>.
     * @alias module:model/UpdateUniversityModel
     * @param curUniversityID {String} 
     */
    constructor(curUniversityID) { 
        
        UpdateUniversityModel.initialize(this, curUniversityID);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, curUniversityID) { 
        obj['curUniversityID'] = curUniversityID;
    }

    /**
     * Constructs a <code>UpdateUniversityModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UpdateUniversityModel} obj Optional instance to populate.
     * @return {module:model/UpdateUniversityModel} The populated <code>UpdateUniversityModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UpdateUniversityModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('curUniversityID')) {
                obj['curUniversityID'] = ApiClient.convertToType(data['curUniversityID'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UpdateUniversityModel.prototype['_id'] = undefined;

/**
 * @member {String} curUniversityID
 */
UpdateUniversityModel.prototype['curUniversityID'] = undefined;






export default UpdateUniversityModel;

