/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The UserAPIModel model module.
 * @module model/UserAPIModel
 * @version 1.0.0
 */
class UserAPIModel {
    /**
     * Constructs a new <code>UserAPIModel</code>.
     * @alias module:model/UserAPIModel
     */
    constructor() { 
        
        UserAPIModel.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>UserAPIModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserAPIModel} obj Optional instance to populate.
     * @return {module:model/UserAPIModel} The populated <code>UserAPIModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserAPIModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('userGroup')) {
                obj['userGroup'] = ApiClient.convertToType(data['userGroup'], 'String');
            }
            if (data.hasOwnProperty('curSemesterID')) {
                obj['curSemesterID'] = ApiClient.convertToType(data['curSemesterID'], 'String');
            }
            if (data.hasOwnProperty('curUniversityID')) {
                obj['curUniversityID'] = ApiClient.convertToType(data['curUniversityID'], 'String');
            }
            if (data.hasOwnProperty('entranceYear')) {
                obj['entranceYear'] = ApiClient.convertToType(data['entranceYear'], 'Number');
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UserAPIModel.prototype['_id'] = undefined;

/**
 * @member {String} email
 */
UserAPIModel.prototype['email'] = undefined;

/**
 * @member {String} userGroup
 */
UserAPIModel.prototype['userGroup'] = undefined;

/**
 * @member {String} curSemesterID
 */
UserAPIModel.prototype['curSemesterID'] = undefined;

/**
 * @member {String} curUniversityID
 */
UserAPIModel.prototype['curUniversityID'] = undefined;

/**
 * @member {Number} entranceYear
 */
UserAPIModel.prototype['entranceYear'] = undefined;






export default UserAPIModel;

