/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import LessonModel from './LessonModel';

/**
 * The UserSemesterModel model module.
 * @module model/UserSemesterModel
 * @version 1.0.0
 */
class UserSemesterModel {
    /**
     * Constructs a new <code>UserSemesterModel</code>.
     * @alias module:model/UserSemesterModel
     * @param name {String} 
     * @param startDate {Date} 
     * @param endDate {Date} 
     * @param startHour {String} 
     * @param dLesson {Number} 
     * @param dBreak {Number} 
     * @param slotCount {Number} 
     */
    constructor(name, startDate, endDate, startHour, dLesson, dBreak, slotCount) { 
        
        UserSemesterModel.initialize(this, name, startDate, endDate, startHour, dLesson, dBreak, slotCount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, startDate, endDate, startHour, dLesson, dBreak, slotCount) { 
        obj['name'] = name;
        obj['startDate'] = startDate;
        obj['endDate'] = endDate;
        obj['startHour'] = startHour;
        obj['dLesson'] = dLesson;
        obj['dBreak'] = dBreak;
        obj['slotCount'] = slotCount;
    }

    /**
     * Constructs a <code>UserSemesterModel</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/UserSemesterModel} obj Optional instance to populate.
     * @return {module:model/UserSemesterModel} The populated <code>UserSemesterModel</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new UserSemesterModel();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('startDate')) {
                obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
            }
            if (data.hasOwnProperty('endDate')) {
                obj['endDate'] = ApiClient.convertToType(data['endDate'], 'Date');
            }
            if (data.hasOwnProperty('startHour')) {
                obj['startHour'] = ApiClient.convertToType(data['startHour'], 'String');
            }
            if (data.hasOwnProperty('dLesson')) {
                obj['dLesson'] = ApiClient.convertToType(data['dLesson'], 'Number');
            }
            if (data.hasOwnProperty('dBreak')) {
                obj['dBreak'] = ApiClient.convertToType(data['dBreak'], 'Number');
            }
            if (data.hasOwnProperty('slotCount')) {
                obj['slotCount'] = ApiClient.convertToType(data['slotCount'], 'Number');
            }
            if (data.hasOwnProperty('lessons')) {
                obj['lessons'] = ApiClient.convertToType(data['lessons'], [LessonModel]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
UserSemesterModel.prototype['_id'] = undefined;

/**
 * @member {String} name
 */
UserSemesterModel.prototype['name'] = undefined;

/**
 * @member {Date} startDate
 */
UserSemesterModel.prototype['startDate'] = undefined;

/**
 * @member {Date} endDate
 */
UserSemesterModel.prototype['endDate'] = undefined;

/**
 * @member {String} startHour
 */
UserSemesterModel.prototype['startHour'] = undefined;

/**
 * @member {Number} dLesson
 */
UserSemesterModel.prototype['dLesson'] = undefined;

/**
 * @member {Number} dBreak
 */
UserSemesterModel.prototype['dBreak'] = undefined;

/**
 * @member {Number} slotCount
 */
UserSemesterModel.prototype['slotCount'] = undefined;

/**
 * @member {Array.<module:model/LessonModel>} lessons
 */
UserSemesterModel.prototype['lessons'] = undefined;






export default UserSemesterModel;

