/**
 * kucukdevapi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import HTTPValidationError from '../model/HTTPValidationError';
import Message from '../model/Message';

/**
* Scheduler service.
* @module api/SchedulerApi
* @version 1.0.0
*/
export default class SchedulerApi {

    /**
    * Constructs a new SchedulerApi. 
    * @alias module:api/SchedulerApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the createSchedule operation.
     * @callback module:api/SchedulerApi~createScheduleCallback
     * @param {String} error Error message, if any.
     * @param {Array.<{String: Number}>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Schedule
     * Create schedules for given lessons
     * @param {String} unid 
     * @param {Array.<String>} requestBody 
     * @param {module:api/SchedulerApi~createScheduleCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<{String: Number}>}
     */
    createSchedule(unid, requestBody, callback) {
      let postBody = requestBody;
      // verify the required parameter 'unid' is set
      if (unid === undefined || unid === null) {
        throw new Error("Missing the required parameter 'unid' when calling createSchedule");
      }
      // verify the required parameter 'requestBody' is set
      if (requestBody === undefined || requestBody === null) {
        throw new Error("Missing the required parameter 'requestBody' when calling createSchedule");
      }

      let pathParams = {
        'unid': unid
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = [{'String': 'Number'}];
      return this.apiClient.callApi(
        '/universities/{unid}/schedule', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
